name: Fix restrict-volume-types

on:
  workflow_dispatch:

jobs:
  fix:
    uses: nirmata/pipeline-scanning/.github/workflows/install-remediator.yml@helm-app
    with:
      restrict_volume_types: true
    secrets: inherit
