name: Fix disallow-privilege-escalation

on:
  workflow_dispatch:

jobs:
  fix:
    uses: nirmata/pipeline-scanning/.github/workflows/install-remediator.yml@helm-app
    with:
      disallow_privilege_escalation: true
    secrets: inherit
