name: Fix disallow-privilege-escalation

on:
  workflow_dispatch:

jobs:
  fix:
    uses: ./.github/workflows/install-remediator.yml
    with:
      disallow_privilege_escalation: true
    secrets:
      NIRMATA_SERVICE_ACCOUNT_TOKEN: ${{ secrets.NIRMATA_SERVICE_ACCOUNT_TOKEN }}
      PAT: ${{ secrets.PAT }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
