name: Fix require-run-as-non-root-user

on:
  workflow_dispatch:

jobs:
  fix:
    uses: ./.github/workflows/install-remediator.yml
    with:
      require_run_as_non_root_user: true
    secrets:
      NIRMATA_SERVICE_ACCOUNT_TOKEN: ${{ secrets.NIRMATA_SERVICE_ACCOUNT_TOKEN }}
      PAT: ${{ secrets.PAT }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
