name: Fix require-requests-limits

on:
  workflow_dispatch:

jobs:
  fix:
    uses: ./.github/workflows/install-remediator.yml
    with:
      require_requests_limits: true
    secrets:
      NIRMATA_SERVICE_ACCOUNT_TOKEN: ${{ secrets.NIRMATA_SERVICE_ACCOUNT_TOKEN }}
      PAT: ${{ secrets.PAT }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
